name: timeseries-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9s
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tensorflow
  - pip
  - pip:
    - tensorflow-addons
    - jsonschema
